language: python
sudo: false
install: 
  - pip install tox
env:
  - TOX_ENV=py36
  - TOX_ENV=py34
  - TOX_ENV=py27
script: 
  - tox -e $TOX_ENV
branches:
  only:
      - master  
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.6
